version: '3'
services:
  backend-app:
    container_name: express
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: '7000'
      HOST: '0.0.0.0'
    ports:
      - 7002:7002
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    restart: always